# Generated by Django 5.2.10 on 2026-02-04 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_commentmodel_author_alter_imagemodel_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='app.productcategory'),
        ),
    ]
